(()=>{'use strict';
const E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const titles=['표지·목차·제출문','성능점검 계획서','성능점검 결과보고서','성능점검표','기계설비 시스템 검토','성능개선 계획 수립','에너지사용량 분석·절감 방안'];
const fields=[['현장명','주소','관리주체','수행기관','보고서번호','대상기간','점검시작일','점검종료일','제출일','점검자','확인자','연면적','세대수','사용승인일','제출문'],['수행목적','수행범위','인력투입계획','투입인력산정','점검일정','점검장비현황','안전확보방안','품질관리방안'],['종합의견','자료검토결과','점검제약사항','조치사항'],[],['유지관리지침서 적정성','시스템 작동상태','설계값과 측정값 검토'],['내구연수 및 노후도','미흡사항 및 조치계획','연도별 세부개선 계획'],['분석기간','에너지원·단위','에너지 분석의견','에너지 절감 방안']];
let d={version:2,info:{},equipment:[],energy:[]},tab=0,selected='',db,queue=Promise.resolve();
const itemPositions=new Map();
const root=()=>document.getElementById('reportComposerPage');
function save(){const snapshot=structuredClone(d);queue=queue.catch(()=>{}).then(()=>new Promise((ok,no)=>{let tx=db.transaction('reports','readwrite');tx.objectStore('reports').put(snapshot,'current');tx.oncomplete=()=>{status('저장됨 · 이 기기');ok()};tx.onerror=()=>{status('저장 실패: 백업을 다운로드하세요');no(tx.error)}}));return queue}
function status(s){let el=document.getElementById('reStatus');if(el)el.textContent=s}
function input(key,value,large=false){return large?`<textarea data-info="${E(key)}">${E(value)}</textarea>`:`<input data-info="${E(key)}" value="${E(value)}">`}
function itemField(i,k,v,large=false){return large?`<textarea data-item="${i}" data-key="${k}">${E(v)}</textarea>`:`<input data-item="${i}" data-key="${k}" value="${E(v)}">`}
function equip(){return d.equipment.find(e=>e.uid===selected)}
function render(){if(!root())return;root().innerHTML=`<div class="re"><header><h2>국토부 매뉴얼 · 보고서 작성</h2><p>현장정보 입력 → 설비번호 등록 → 점검·사진 작성 → 전체 보고서 출력</p><div class="reTools"><button data-action="preview">전체 보고서 미리보기 / PDF</button><button data-action="excel">작성 데이터 Excel</button><button data-action="backup">사진 포함 백업</button><label class="reBtn">백업 불러오기<input type="file" id="reRestore" accept=".json" hidden></label><span id="reStatus">이 기기에 저장 · 다른 기기에는 백업 파일로 이동</span></div></header><nav>${titles.map((t,i)=>`<button data-tab="${i}" class="${i===tab?'chosen':''}">${i}. ${t}</button>`).join('')}</nav><h3>${titles[tab]}</h3>${tab===3?equipmentUI():`<div class="reGrid">${fields[tab].map(k=>`<label>${k}${input(k,d.info[k]||'',tab!==0||k==='제출문')}</label>`).join('')}</div>${tab===6?energyUI():''}`}</div>`;bind()}
function energyUI(){return `<h4>월별 사용량 (동일 단위로 입력)</h4><div class="reGrid">${Array.from({length:12},(_,i)=>`<label>${i+1}월<input type="number" min="0" step="any" data-month="${i}" value="${E(d.energy[i]??'')}"></label>`).join('')}</div>`}
function equipmentUI(){const e=equip();const current=currentItem(e);return `<div class="reAdd"><label>설비종류<select id="reType">${Object.keys(CHECK_TEMPLATES).map(t=>`<option>${E(t)}</option>`).join('')}</select></label><label>설비번호 (쉼표로 여러 대 등록)<input id="reNumbers" placeholder="CH-1, CH-2, CH-3"></label><button data-action="add">점검표 자동 생성</button></div><p>설비번호별로 1부씩 생성됩니다. 동일한 번호는 중복 등록되지 않습니다. 판정은 직접 선택하세요.</p><div class="reTools">${d.equipment.map(x=>`<button data-equip="${x.uid}" class="${x.uid===selected?'chosen':''}">${E(x.type)} · ${E(x.number)}</button>`).join('')}</div>${e?`<h3>${E(e.type)} / ${E(e.number)}</h3><div class="reGrid">${['용도','설치위치','제조사','설치년도','사양','점검일','점검자'].map(k=>`<label>${k}<input data-equipment="${k}" value="${E(e[k]||'')}"></label>`).join('')}</div><label>설계·측정값 (항목 / 설계값 / 측정값 / 단위)<textarea data-equipment="측정값">${E(e['측정값']||'')}</textarea></label><button data-action="remove">이 설비 삭제</button>${pager(e,current)}<div id="reSwipePage" class="reSwipePage" aria-label="점검항목" tabindex="-1">${e.items.map((x,i)=>i===current?`<article class="reCheck"><h4>${E(x.title)}</h4><details><summary>원본 양식의 점검방법·기준</summary><pre>${E(x.criteria)}</pre></details><label>판정<select data-item="${i}" data-key="result">${['미작성','적합','미흡','조치필요','해당없음','측정불가'].map(v=>`<option ${x.result===v?'selected':''}>${v}</option>`).join('')}</select></label><label>측정값 / 확인내용${itemField(i,'measurement',x.measurement)}</label><div class="rePhotos">${['현황','적합','미흡사항'].map((p,j)=>`<section><b>${p} 사진</b><button type="button" class="rePhotoSlot ${x.photos[j]?'rePhotoFilled':''}" data-photo-slot="${i}:${j}" aria-label="${p} 사진 ${x.photos[j]?'교체':'첨부'}">${x.photos[j]?`<img src="${x.photos[j]}" alt="${p} 사진">`:`<span class="rePhotoEmpty">＋<strong>사진 칸을 눌러 첨부</strong><small>사진 선택 또는 카메라 촬영</small></span>`}</button>${x.photos[j]?`<button type="button" data-photo-remove="${i}:${j}">사진 삭제</button>`:''}<label>${p} 사유${itemField(i,'reason'+j,x['reason'+j],true)}</label></section>`).join('')}</div><label>조치사항${itemField(i,'action',x.action,true)}</label></article>`:'').join('')}</div>${pager(e,current)}`:'<p>설비종류와 실제 설비번호를 입력하면 원본 양식의 점검항목이 자동 생성됩니다.</p>'}`}

function currentItem(e){return e?.items.length?Math.min(Math.max(itemPositions.get(e.uid)||0,0),e.items.length-1):0}
function pager(e,i){return `<div class="rePager"><button type="button" data-step="-1" ${i===0?'disabled':''} aria-label="이전 점검항목">‹ 이전</button><span role="status" aria-live="polite">${E(e.number)} · ${i+1} / ${e.items.length}<small>왼쪽으로 밀면 다음 항목</small></span><button type="button" data-step="1" ${i>=e.items.length-1?'disabled':''} aria-label="다음 점검항목">다음 ›</button></div>`}
function moveItem(step){const e=equip();if(!e)return;const next=currentItem(e)+step;if(next<0||next>=e.items.length)return;itemPositions.set(e.uid,next);render();const panel=document.getElementById('reSwipePage');panel?.scrollIntoView({block:'start',behavior:'auto'});panel?.focus({preventScroll:true})}
function swipeStep(dx,dy){return Math.abs(dx)>=70&&Math.abs(dx)>Math.abs(dy)*1.6?(dx<0?1:-1):0}
function bindPager(){
 root().querySelectorAll('[data-step]').forEach(el=>el.onclick=()=>moveItem(Number(el.dataset.step)));
 const panel=document.getElementById('reSwipePage');if(!panel)return;
 let start=null;
 const isEditing=el=>el.closest('input,textarea,select,button,a,summary,[contenteditable="true"]');
 panel.addEventListener('pointerdown',ev=>{if(!ev.isPrimary||ev.pointerType==='mouse'||isEditing(ev.target)){start=null;return}start={x:ev.clientX,y:ev.clientY,id:ev.pointerId}});
 panel.addEventListener('pointerup',ev=>{if(!start||ev.pointerId!==start.id)return;const step=swipeStep(ev.clientX-start.x,ev.clientY-start.y);start=null;if(step)moveItem(step)});
 panel.addEventListener('pointercancel',()=>{start=null});
 panel.addEventListener('keydown',ev=>{if(isEditing(ev.target))return;if(ev.key==='ArrowRight'||ev.key==='ArrowLeft'){ev.preventDefault();moveItem(ev.key==='ArrowRight'?1:-1)}});
}

function bind(){bindPager();root().querySelectorAll('[data-tab]').forEach(el=>el.onclick=()=>{tab=+el.dataset.tab;render()});root().querySelectorAll('[data-info]').forEach(el=>el.oninput=()=>{d.info[el.dataset.info]=el.value;save()});root().querySelectorAll('[data-month]').forEach(el=>el.oninput=()=>{d.energy[+el.dataset.month]=el.value;save()});root().querySelectorAll('[data-equip]').forEach(el=>el.onclick=()=>{selected=el.dataset.equip;render()});root().querySelectorAll('[data-equipment]').forEach(el=>el.oninput=()=>{equip()[el.dataset.equipment]=el.value;save()});root().querySelectorAll('[data-item]').forEach(el=>el.oninput=()=>{equip().items[+el.dataset.item][el.dataset.key]=el.value;save()});root().querySelectorAll('[data-photo-slot]').forEach(el=>el.onclick=()=>openPhotoPicker(el));root().querySelectorAll('[data-photo-remove]').forEach(el=>el.onclick=()=>{let [i,j]=el.dataset.photoRemove.split(':').map(Number);equip().items[i].photos[j]='';save();render()});root().querySelectorAll('[data-action]').forEach(el=>el.onclick=()=>actions[el.dataset.action]());document.getElementById('reRestore').onchange=restore}
const actions={add(){const type=document.getElementById('reType').value,numbers=document.getElementById('reNumbers').value.split(/[,，\n]/).map(v=>v.trim()).filter(Boolean);if(!numbers.length)return alert('실제 설비번호를 입력하세요.');if(new Set(numbers).size!==numbers.length||numbers.some(n=>d.equipment.some(e=>e.number===n)))return alert('중복 설비번호가 있습니다. 번호를 확인하세요.');for(const number of numbers){let e={uid:crypto.randomUUID(),type,number,items:CHECK_TEMPLATES[type].map(x=>({...x,result:'미작성',photos:['','',''],reason0:'',reason1:'',reason2:'',measurement:'',action:''}))};d.equipment.push(e);selected=e.uid}save();render()},remove(){if(!confirm('이 설비의 사진과 점검 기록을 삭제할까요?'))return;d.equipment=d.equipment.filter(e=>e.uid!==selected);selected=d.equipment[0]?.uid||'';save();render()},backup(){download(JSON.stringify(d),fileName()+'.json','application/json')},preview(){preview()},excel(){if(!window.XLSX)return alert('Excel 구성요소를 불러오지 못했습니다. 인터넷 연결 후 다시 시도하세요.');const w=XLSX.utils.book_new();XLSX.utils.book_append_sheet(w,XLSX.utils.aoa_to_sheet([['항목','내용'],...Object.entries(d.info)]),'보고서 입력');XLSX.utils.book_append_sheet(w,XLSX.utils.aoa_to_sheet([['설비종류','설비번호','점검항목','방법·기준','판정','측정값','현황사유','적합사유','미흡사유','조치사항'],...d.equipment.flatMap(e=>e.items.map(i=>[e.type,e.number,i.title,i.criteria,i.result,i.measurement,i.reason0,i.reason1,i.reason2,i.action]))]),'설비별 점검');XLSX.utils.book_append_sheet(w,XLSX.utils.aoa_to_sheet([['월','사용량'],...Array.from({length:12},(_,i)=>[i+1,d.energy[i]===''||d.energy[i]==null?'':Number(d.energy[i])])]),'에너지사용량');XLSX.writeFile(w,fileName()+'.xlsx')}};
function fileName(){return (d.info['현장명']||'성능점검보고서').replace(/[\\/:*?"<>|]/g,'_')}
function download(data,name,type){let a=document.createElement('a'),url=URL.createObjectURL(new Blob([data],{type}));a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000)}

function usePhoneCamera(n=navigator){return !!(n.userAgentData?.mobile||/Android|iPhone|iPad|iPod/i.test(n.userAgent)||(n.platform==='MacIntel'&&n.maxTouchPoints>1))}
function openPhotoPicker(slot){
 const target=equip(),index=slot.dataset.photoSlot;
 const dlg=document.createElement('dialog');dlg.className='rePhotoDialog';
 dlg.innerHTML=`<div class="rePhotoDialogBody"><h3>사진 첨부</h3><p>해당 칸에 넣을 사진을 선택하세요.</p><button type="button" data-source="gallery">사진 선택 · 갤러리 / 파일</button><button type="button" data-source="camera">카메라로 촬영</button><div class="reCamera" hidden><video autoplay muted playsinline></video><button type="button" data-shutter disabled>촬영하여 첨부</button></div><p role="status" class="reCameraMessage"></p><button type="button" data-close>취소</button></div>`;
 document.body.appendChild(dlg);let stream=null,closed=false;
 function cleanup(){closed=true;stream?.getTracks().forEach(t=>t.stop());dlg.remove();if(slot.isConnected)slot.focus()}
 dlg.addEventListener('close',cleanup,{once:true});dlg.querySelector('[data-close]').onclick=()=>dlg.close();
 function choose(capture){const input=document.createElement('input');input.type='file';input.accept='image/*';input.hidden=true;if(capture)input.setAttribute('capture','environment');dlg.appendChild(input);input.onchange=()=>{const f=input.files[0];if(!f){input.remove();return}photo({files:[f],dataset:{photo:index}},target);dlg.close()};input.addEventListener('cancel',()=>input.remove(),{once:true});input.click()}
 dlg.querySelector('[data-source="gallery"]').onclick=()=>choose(false);
 if(usePhoneCamera()){
  dlg.querySelector('[data-source="camera"]').textContent='휴대폰 카메라로 촬영';
  dlg.querySelector('.reCameraMessage').textContent='휴대폰 촬영 화면에서 방향과 줌을 조절한 뒤 사진 사용 또는 완료를 선택하세요.';
 }
 dlg.querySelector('[data-source="camera"]').onclick=async()=>{
  if(usePhoneCamera()){choose(true);return} 
  const msg=dlg.querySelector('.reCameraMessage');
  if(!navigator.mediaDevices?.getUserMedia){msg.textContent='이 환경에서는 카메라를 열 수 없습니다. HTTPS로 접속하거나 사진 선택을 이용하세요.';return}
  const cam=dlg.querySelector('[data-source="camera"]');cam.disabled=true;msg.textContent='카메라 연결 중…';
  try{const incoming=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1280},height:{ideal:720}},audio:false});if(closed){incoming.getTracks().forEach(t=>t.stop());return}stream=incoming;const video=dlg.querySelector('video');video.muted=true;video.autoplay=true;video.playsInline=true;video.setAttribute('webkit-playsinline','');video.srcObject=stream;dlg.querySelector('.reCamera').hidden=false;
   await cameraPreviewReady(video,()=>closed);
   if(closed)return;dlg.querySelector('[data-shutter]').disabled=false;msg.textContent='영상이 보이는지 확인한 뒤 촬영하여 첨부를 누르세요.';
  }catch(err){stream?.getTracks().forEach(t=>t.stop());if(!closed){dlg.querySelector('[data-shutter]').disabled=true;dlg.querySelector('.reCamera').hidden=true;const messages={NotAllowedError:'카메라 사용이 허용되지 않았습니다. 브라우저의 사이트 카메라 권한을 허용해 주세요.',NotFoundError:'사용할 수 있는 카메라를 찾지 못했습니다.',NotReadableError:'카메라를 사용할 수 없습니다. 다른 촬영 앱을 닫고 다시 시도해 주세요.',PreviewTimeout:'카메라 영상이 도착하지 않았습니다. 다시 시도하거나 기본 카메라 앱으로 촬영 후 사진 선택으로 첨부해 주세요.'};msg.textContent=messages[err.name]||'카메라를 열지 못했습니다. 권한과 연결을 확인하거나 사진 선택으로 첨부해 주세요.';cam.disabled=false;cam.textContent='카메라 다시 연결'}}
 };
 dlg.querySelector('[data-shutter]').onclick=()=>{const video=dlg.querySelector('video');if(!video.videoWidth)return;const canvas=document.createElement('canvas');canvas.width=video.videoWidth;canvas.height=video.videoHeight;canvas.getContext('2d').drawImage(video,0,0);canvas.toBlob(blob=>{if(!blob||closed)return;photo({files:[blob],dataset:{photo:index}},target);dlg.close()},'image/jpeg',.9)};
 dlg.showModal();
}

function cameraPreviewReady(video,isClosed){
 return new Promise((resolve,reject)=>{
  let done=false,timer;
  function finish(error){if(done)return;done=true;clearInterval(timer);error?reject(error):resolve()}
  const started=Date.now();
  timer=setInterval(()=>{if(isClosed())return finish(Object.assign(new Error('닫힘'),{name:'AbortError'}));if(video.readyState>=2&&video.videoWidth>0&&video.videoHeight>0&&!video.paused)return finish();if(Date.now()-started>12000)finish(Object.assign(new Error('영상 대기 시간 초과'),{name:'PreviewTimeout'}))},100);
  video.play().catch(finish);
 });
}

async function photo(el,target=equip()){const f=el.files[0];if(!f)return;const e=target,[i,j]=el.dataset.photo.split(':').map(Number);try{const bm=await createImageBitmap(f,{imageOrientation:'from-image'}),scale=Math.min(1,1600/Math.max(bm.width,bm.height)),canvas=document.createElement('canvas');canvas.width=Math.round(bm.width*scale);canvas.height=Math.round(bm.height*scale);canvas.getContext('2d').drawImage(bm,0,0,canvas.width,canvas.height);e.items[i].photos[j]=canvas.toDataURL('image/jpeg',.85);bm.close();await save();render()}catch(err){alert('사진을 처리하지 못했습니다. JPG 또는 PNG 파일과 저장공간을 확인하세요.')}}
async function restore(ev){try{const v=JSON.parse(await ev.target.files[0].text());if(v.version!==2||!v.info||!Array.isArray(v.equipment)||!Array.isArray(v.energy)||v.equipment.some(e=>!e.uid||!e.number||!e.type||!Array.isArray(e.items)||e.items.some(i=>!Array.isArray(i.photos)||i.photos.some(p=>p&&!/^data:image\/(jpeg|png|webp);base64,[A-Za-z0-9+/=]+$/.test(p)))))throw Error();if(!confirm('현재 작성 내용을 백업 파일로 교체할까요?'))return;d=v;selected=d.equipment[0]?.uid||'';await save();render()}catch(e){alert('올바른 보고서 백업 파일인지 확인하세요.')}}
function table(rows){return '<table>'+rows.map(r=>'<tr>'+r.map(v=>'<td>'+E(v).replace(/\n/g,'<br>')+'</td>').join('')+'</tr>').join('')+'</table>'}
function textSections(n){return fields[n].map(k=>'<h3>'+E(k)+'</h3><p>'+E(d.info[k]||'미입력').replace(/\n/g,'<br>')+'</p>').join('')}
function page(title,content){return `<section class="paper"><div class="paperhead">${E(d.info['현장명']||'현장명 미입력')} · 기계설비 성능점검 보고서</div><h2>${title}</h2>${content}</section>`}
function report(){let html=page('기계설비 성능점검 보고서',table(fields[0].filter(k=>k!=='제출문').map(k=>[k,d.info[k]||'미입력'])));html+=page('점검완료 제출문','<p>'+E(d.info['제출문']||'미입력').replace(/\n/g,'<br>')+'</p>');html+=page('목차','<ol>'+titles.map(t=>'<li>'+E(t)+'</li>').join('')+'</ol>');html+=page('Ⅰ. 성능점검 계획서',textSections(1)+ '<h3>점검대상 기계설비 수량</h3>'+table([['설비종류','등록대수'],...Object.keys(CHECK_TEMPLATES).filter(t=>d.equipment.some(e=>e.type===t)).map(t=>[t,d.equipment.filter(e=>e.type===t).length])])+'<h3>설비 현황</h3>'+table([['종류','번호','용도','설치위치'],...d.equipment.map(e=>[e.type,e.number,e['용도'],e['설치위치']]) ]));html+=page('Ⅱ. 성능점검 결과보고서',textSections(2)+table([['종류','번호','전체항목','작성항목','미흡·조치필요'],...d.equipment.map(e=>[e.type,e.number,e.items.length,e.items.filter(i=>i.result!=='미작성').length,e.items.filter(i=>['미흡','조치필요'].includes(i.result)).length]) ]));for(const e of d.equipment){html+=page(`Ⅲ. ${E(e.type)} 성능점검표 · ${E(e.number)}`,table([['설비번호',e.number],...['용도','설치위치','제조사','설치년도','사양','점검일','점검자','측정값'].map(k=>[k,e[k]||'미입력'])])+table([['점검항목','판정'],...e.items.map(i=>[i.title,i.result])]));for(const i of e.items){html+=page(`${E(e.type)} · ${E(e.number)} / ${E(i.title)}`,table([['점검방법·기준',i.criteria],['판정',i.result],['측정값·확인내용',i.measurement||'미입력']])+`<div class="photos">${['현황','적합','미흡사항'].map((name,j)=>`<section><h4>${name} 사진</h4>${i.photos[j]?`<div class="reportPhotoFrame"><img src="${i.photos[j]}" alt="${name}"></div>`:'<div class="noPhoto">사진 미첨부</div>'}<p>사유: ${E(i['reason'+j]||'미입력').replace(/\n/g,'<br>')}</p></section>`).join('')}</div>`+table([['조치사항',i.action||'미입력']]))}}html+=page('Ⅳ. 기계설비 시스템 검토',textSections(4));html+=page('Ⅴ. 성능개선 계획 수립',textSections(5)+table([['설비번호','점검항목','판정','조치사항'],...d.equipment.flatMap(e=>e.items.filter(i=>['미흡','조치필요'].includes(i.result)).map(i=>[e.number,i.title,i.result,i.action]))]));html+=page('Ⅵ. 에너지사용량 분석',textSections(6).split('<h3>에너지 절감 방안</h3>')[0]+table([['월','사용량'],...Array.from({length:12},(_,i)=>[i+1,d.energy[i]??'미입력']),['입력월 합계',d.energy.reduce((s,x)=>s+(Number(x)||0),0)]]));html+=page('Ⅶ. 에너지 절감 방안','<p>'+E(d.info['에너지 절감 방안']||'미입력').replace(/\n/g,'<br>')+'</p>');return html}
function preview(){const w=window.open('','_blank');if(!w)return alert('팝업을 허용한 뒤 다시 시도하세요.');w.document.write(`<!doctype html><html lang="ko"><meta charset="utf-8"><title>${E(fileName())}</title><style>body{font-family:Arial,'Malgun Gothic',sans-serif;background:#e9edf2;color:#111;line-height:1.6}.paper{background:white;width:174mm;min-height:240mm;margin:20px auto;padding:18mm;break-after:page}.paperhead{font-size:12px;border-bottom:1px solid #555}h2{font-size:23px;margin:24px 0}h3{font-size:17px}table{border-collapse:collapse;width:100%;margin:16px 0;table-layout:fixed}td{border:1px solid #777;padding:7px;white-space:pre-wrap;overflow-wrap:anywhere;vertical-align:top}td:first-child{background:#e4eef5;width:28%}tr{break-inside:avoid}.photos{display:grid;grid-template-columns:repeat(3,1fr);gap:0;break-inside:avoid}.photos section{border:1px solid #777;min-width:0}.photos h4{margin:0;text-align:center;background:#e4eef5}.reportPhotoFrame{box-sizing:border-box;width:100%;height:190px;padding:2px;background:#fff;overflow:hidden}.photos .reportPhotoFrame img{display:block;box-sizing:border-box;width:100%;height:100%;margin:0;padding:0;object-fit:fill;border:0;border-radius:0}.noPhoto{width:100%;height:190px}.noPhoto{display:grid;place-items:center;color:#777}.photos p{padding:8px;overflow-wrap:anywhere}.tools{position:sticky;top:0;background:#183e63;color:#fff;padding:12px}button{padding:10px}p{white-space:pre-wrap;overflow-wrap:anywhere}@page{size:A4;margin:12mm}@media print{body{background:white}.tools{display:none}.paper{width:auto;min-height:0;margin:0;padding:0}.paper:last-child{break-after:auto}}</style><div class="tools"><button id="printReport">PDF로 저장 / 인쇄</button> 인쇄 설정에서 A4를 선택하세요. 미입력 항목은 제출 전 확인하세요.</div>${report()}<script>document.getElementById('printReport').onclick=async()=>{await Promise.all(Array.from(document.images).map(i=>i.decode().catch(()=>{})));window.print()};<\/script></html>`);w.document.close()}
let request=indexedDB.open('mechanical-report-v2',1);request.onupgradeneeded=()=>request.result.createObjectStore('reports');request.onerror=()=>alert('보고서 저장공간을 열지 못했습니다. 브라우저 저장 설정을 확인하세요.');request.onsuccess=()=>{db=request.result;let get=db.transaction('reports').objectStore('reports').get('current');get.onsuccess=()=>{if(get.result)d=get.result;selected=d.equipment[0]?.uid||'';window.renderComposer=render;window.openLandManualReport=(page,key)=>{tab=['cover','plan','result','sheet','system','improve','energy'].indexOf(key);if(tab<0)tab=0;showReportPage('composer')};if(root()?.classList.contains('active'))render()}};
})();
